### ISSUE TITLE
Ошибка при колпиляции ESP 32

### ISSUE THREAD

**Issue by Igor-kr** [invandy/Oregon_NR#13]
Спасибо за библиотеку. 
На Ардуино работает, хочу отправлять данные в HomeAssistant используя ESPHome но на первом этапе 

при компиляции для ESP32 выдает ошибку:

/igor/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/variants/nodemcu-32s -I/Users/igor/Documents/Arduino/libraries/Oregon_NR /var/folders/ft/ghv3fbyd6_xbwrbg8k4pm2_r0000gn/T/arduino_build_527710/sketch/Receiver.ino.cpp -o /var/folders/ft/ghv3fbyd6_xbwrbg8k4pm2_r0000gn/T/arduino_build_527710/preproc/ctags_target_for_gcc_minus_e.cpp -DARDUINO_LIB_DISCOVERY_PHASE
Receiver:3:36: error: missing expression between '(' and ')'
 #if defined ( ESP8266 ) || ( ESP32 )// Для Wemos
                                    ^
Используем библиотеку Oregon_NR версии 20.10.10 из папки: /Users/igor/Documents/Arduino/libraries/Oregon_NR 
exit status 1
missing expression between '(' and ')'

**Comment by invandy** [comment]
Скорее всего у вас не определено ESP8266 или ESP32
Попробуйте заменить на 
#if defined ( ESP32 )
Если не поможет, можно попробовать убрать все предпроцессорные директивы и оставить только нужный конструктор.

**Comment by invandy** [comment]
Заодно скачайте библиотеку заново, там как раз для ESP только что подправил скетч.

**Comment by Igor-kr** [comment]
Здравствуйте,

#include <Oregon_NR.h>
#define ESP32
#if defined ( ESP8266 ) || ( ESP32 )// Для Wemos

выдает ошибку

#include <Oregon_NR.h>
#define ESP32
#if defined ( ESP32 ) || ( ESP8266 )// Для Wemos

компилируется в IDE Arduino и работает нормально 

При попытке скомпилировать для ESPHOME 

файл my_oregon.h

#include "esphome.h"
#include "Oregon_NR.h"
//Oregon_NR oregon(13, 13, 2, true);
class MyOregonSensor : public PollingComponent {
 public:
  Oregon_NR oregon(13,13,2,true);
  
//   Oregon_NR oregon(13, 13,          // приёмник на выводе D7 (GPIO13)
//                         2, true,    // Светодиод на D2 подтянут к +пит(true). Если светодиод не нужен, то номер вывода - 255
//                         50, true);  // Буфер на приём посылки из 50 ниблов, включена сборка пакетов для v2

  Sensor *temperature_sensor = new Sensor();
  Sensor *humidity_sensor = new Sensor();

  MyOregonSensor() : PollingComponent(15000) { }

  void setup() override {
    
    oregon.start(); 
//    oregon.receiver_dump = 0;       //true - Включает "осциллограф" - отображение данных, полученных с приёмника
  }

  void update() override {
    // This is the actual sensor reading logic.
    float temperature = oregon.sens_tmp;
    temperature_sensor->publish_state(temperature);

    float humidity = oregon.sens_hmdty;
    humidity_sensor->publish_state(humidity);
  }
};

Компилятор ругается на конструктор класса

Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <Oregon_NR> 20.10.7
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling .pioenvs/oregon_rx/src/main.cpp.o
In file included from src/main.cpp:15:0:
src/my_oregon.h:6:20: error: expected identifier before numeric constant
   Oregon_NR oregon(13, 13, 2, true);
                    ^
src/my_oregon.h:6:20: error: expected ',' or '...' before numeric constant
In file included from src/main.cpp:15:0:
src/my_oregon.h: In member function 'virtual void MyOregonSensor::setup()':
src/my_oregon.h:19:5: error: '((MyOregonSensor*)this)->MyOregonSensor::oregon' does not have class type
     oregon.start(); 
     ^
src/my_oregon.h: In member function 'virtual void MyOregonSensor::update()':
src/my_oregon.h:25:25: error: '((MyOregonSensor*)this)->MyOregonSensor::oregon' does not have class type
     float temperature = oregon.sens_tmp;
                         ^
src/my_oregon.h:28:22: error: '((MyOregonSensor*)this)->MyOregonSensor::oregon' does not have class type
     float humidity = oregon.sens_hmdty;
                      ^
src/main.cpp: In lambda function:
src/main.cpp:126:28: error: expected type-specifier before 'MyCustomSensor'
       auto my_sensor = new MyCustomSensor();
                            ^
src/main.cpp:128:72: error: could not convert '{<expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::sensor::Sensor*>'
       return {my_sensor->temperature_sensor, my_sensor->humidity_sensor};
                                                                        ^
Compiling .pioenvs/oregon_rx/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pioenvs/oregon_rx/FrameworkArduino/HardwareSerial.cpp.o
*** [.pioenvs/oregon_rx/src/main.cpp.o] Error 1
Compiling .pioenvs/oregon_rx/FrameworkArduino/IPAddress.cpp.o
========================= [FAILED] Took 150.17 seconds =========================

**Comment by invandy** [comment]
Так я не понял? В Arduino IDE пример с приёмником под ESP32 тоже не компилируется?

**Comment by Igor-kr** [comment]
В Arduino IDE компилируется без ошибок и принимает данные (вижу в мониторе порта).

Когда пытаюсь использовать вашу библиотеку,
создаю Custom Sensor для EspHome и объявляю класс 
Как здесь описано

https://esphome.io/components/sensor/custom.html


```
public:
Oregon_NR oregon(13,13,2,true);
```
Компилятор , они используют PlatformIO ругается на это `(13,13,2,true);`

```
Compiling .pioenvs/oregon_rx/src/main.cpp.o
In file included from src/main.cpp:15:0:
src/my_oregon.h:6:20: error: expected identifier before numeric constant
Oregon_NR oregon(13, 13, 2, true);
^
src/my_oregon.h:6:20: error: expected ',' or '...' before numeric constant


In file included from src/main.cpp:15:0:
src/my_oregon.h: In member function 'virtual void MyOregonSensor::setup()':
src/my_oregon.h:19:5: error: '((MyOregonSensor*)this)->MyOregonSensor::oregon' does not have class type
oregon.start();
^
```


Вот мой заголовочный файл для ESPHOME

```
#include "esphome.h"
#include "Oregon_NR.h"

class MyOregonSensor : public PollingComponent {
 public:
 
  Oregon_NR oregon(13,13,2,true);

  Sensor *temperature_sensor = new Sensor();
  Sensor *humidity_sensor = new Sensor();

  MyOregonSensor() : PollingComponent(15000) { }

  void setup() override {
    
    oregon.start(); 
//    oregon.receiver_dump = 0;       //true - Включает "осциллограф" - отображение данных, полученных с приёмника
  }

  void update() override {
    // This is the actual sensor reading logic.
    float temperature = oregon.sens_tmp;
    temperature_sensor->publish_state(temperature);

    float humidity = oregon.sens_hmdty;
    humidity_sensor->publish_state(humidity);
  }
};

```



```
esphome:
  name: oregon_rx
  platform: ESP32
  board: nodemcu-32s
  includes:
    - "my_oregon.h"
  libraries:
    - "https://github.com/invandy/Oregon_NR.git"  
  

wifi:
  ssid: secret
  password: secret

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: secret
    password: secret

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyOregonSensor();
    App.register_component(my_sensor);
    return {my_sensor->temperature_sensor, my_sensor->humidity_sensor};

  sensors:
  - name: "My Custom Temperature Sensor"
    unit_of_measurement: °C
    accuracy_decimals: 1
  - name: "My Custom Humidity Sensor"
    unit_of_measurement: "%"
    accuracy_decimals: 1
```
Может быть как то по другому можно инициализировать класс?
Извиняюсь за глупые вопросы но не програмист я :)
